export const userData = [
  {
    name: "Micheal John",
    city: "Jaffna",
    desc: "Building Painter",
    exp: "I have 3 years work experience and done some courses",
    online: true,
    profile: "pic1.jpg",
    email: "john@email.com",
    phone: "077383839",
  },
  {
    name: "Lewis Nickoles",
    city: "Vavuniya",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Batticaloa",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: true,
    profile: "pic1.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Kandy",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Colombo",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic1.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Anuradhapura",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Mannar",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Galle",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Badulla",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Jaffna",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Kandy",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Colombo",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Anuradhapura",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Badulla",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Vavuniya",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Vavuniya",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Vavuniya",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Vavuniya",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Vavuniya",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
  {
    name: "Lewis Nickoles",
    city: "Vavuniya",
    desc: "Building Constructor",
    exp: "I have 2 years work experience and done some courses",
    online: false,
    profile: "pic2.jpg",
    email: "lewis@email.com",
    phone: "0769688839",
  },
];
